# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'telaPrincipal.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        MainWindow.setStyleSheet("QMainWindow{\n"
"background-color: white;\n"
"\n"
"}")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.backgroundHeader = QtWidgets.QLabel(self.centralwidget)
        self.backgroundHeader.setGeometry(QtCore.QRect(-20, 0, 831, 111))
        self.backgroundHeader.setStyleSheet("QLabel{\n"
"background-color: #93b4db; \n"
"\n"
"}")
        self.backgroundHeader.setText("")
        self.backgroundHeader.setObjectName("backgroundHeader")
        self.Titulo = QtWidgets.QLabel(self.centralwidget)
        self.Titulo.setGeometry(QtCore.QRect(320, 10, 201, 91))
        self.Titulo.setStyleSheet("QLabel{\n"
"font-size: 16px;\n"
"font: bold;\n"
"font-family: Comic Neue;\n"
"color: black\n"
"\n"
"}")
        self.Titulo.setAlignment(QtCore.Qt.AlignCenter)
        self.Titulo.setObjectName("Titulo")
        self.imagemLogo = QtWidgets.QLabel(self.centralwidget)
        self.imagemLogo.setGeometry(QtCore.QRect(10, 10, 101, 101))
        self.imagemLogo.setText("")
        self.imagemLogo.setPixmap(QtGui.QPixmap("../public/images/cuatroDesarrolladores.png"))
        self.imagemLogo.setScaledContents(True)
        self.imagemLogo.setObjectName("imagemLogo")
        self.tentativas = QtWidgets.QLabel(self.centralwidget)
        self.tentativas.setGeometry(QtCore.QRect(260, 540, 151, 51))
        self.tentativas.setStyleSheet("QLabel{\n"
"font-size: 16px;\n"
"font: bold;\n"
"font-family: Comic Neue;\n"
"\n"
"}")
        self.tentativas.setAlignment(QtCore.Qt.AlignCenter)
        self.tentativas.setObjectName("tentativas")
        self.inputCarro = QtWidgets.QLineEdit(self.centralwidget)
        self.inputCarro.setGeometry(QtCore.QRect(210, 440, 231, 31))
        self.inputCarro.setStyleSheet("QLineEdit{\n"
"border-radius: 5px;\n"
"border: 1px solid black;\n"
"color: black;\n"
"placeholderText-color: black;\n"
"\n"
"}")
        self.inputCarro.setAlignment(QtCore.Qt.AlignCenter)
        self.inputCarro.setObjectName("inputCarro")
        self.imagemCarro = QtWidgets.QLabel(self.centralwidget)
        self.imagemCarro.setGeometry(QtCore.QRect(100, 120, 461, 281))
        self.imagemCarro.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.imagemCarro.setStyleSheet("QLabel{\n"
"border-radius: 8px;\n"
"}")
        self.imagemCarro.setText("")
        self.imagemCarro.setPixmap(QtGui.QPixmap("../public/images/Audi RS7.png"))
        self.imagemCarro.setScaledContents(True)
        self.imagemCarro.setObjectName("imagemCarro")
        self.desistir = QtWidgets.QPushButton(self.centralwidget)
        self.desistir.setGeometry(QtCore.QRect(210, 490, 101, 41))
        self.desistir.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.desistir.setStyleSheet("QPushButton{\n"
"border-radius: 5px;\n"
"color: white;\n"
"background-color: #E53B3B;\n"
"font: bold;\n"
"font-size: 12px;\n"
"\n"
"}")
        self.desistir.setObjectName("desistir")
        self.confirmar = QtWidgets.QPushButton(self.centralwidget)
        self.confirmar.setGeometry(QtCore.QRect(340, 490, 101, 41))
        self.confirmar.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.confirmar.setStyleSheet("QPushButton{\n"
"border-radius: 5px;\n"
"color: white;\n"
"background-color: #90E53B;\n"
"font: bold;\n"
"font-size: 12px;\n"
"\n"
"}")
        self.confirmar.setObjectName("confirmar")
        self.tabelaDicas = QtWidgets.QLabel(self.centralwidget)
        self.tabelaDicas.setGeometry(QtCore.QRect(570, 120, 221, 431))
        self.tabelaDicas.setStyleSheet("QLabel{\n"
"border: 1px solid black;\n"
"border-radius: 5px;\n"
"\n"
"}")
        self.tabelaDicas.setText("")
        self.tabelaDicas.setObjectName("tabelaDicas")
        self.imagemSetinha = QtWidgets.QLabel(self.centralwidget)
        self.imagemSetinha.setGeometry(QtCore.QRect(740, 40, 31, 31))
        self.imagemSetinha.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.imagemSetinha.setText("")
        self.imagemSetinha.setPixmap(QtGui.QPixmap("../public/images/voltar.png"))
        self.imagemSetinha.setScaledContents(True)
        self.imagemSetinha.setObjectName("imagemSetinha")
        self.voltar = QtWidgets.QPushButton(self.centralwidget)
        self.voltar.setGeometry(QtCore.QRect(734, 40, 41, 31))
        self.voltar.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.voltar.setStyleSheet("QPushButton{\n"
"font-size: 14px;\n"
"font: bold;\n"
"border: none;\n"
"\n"
"}")
        self.voltar.setText("")
        self.voltar.setObjectName("voltar")
        self.imagemDica = QtWidgets.QLabel(self.centralwidget)
        self.imagemDica.setGeometry(QtCore.QRect(750, 130, 31, 31))
        self.imagemDica.setText("")
        self.imagemDica.setPixmap(QtGui.QPixmap("../public/images/dica.png"))
        self.imagemDica.setScaledContents(True)
        self.imagemDica.setObjectName("imagemDica")
        self.labelDica = QtWidgets.QLabel(self.centralwidget)
        self.labelDica.setGeometry(QtCore.QRect(650, 130, 51, 31))
        self.labelDica.setStyleSheet("QLabel{\n"
"font-size: 16px;\n"
"font: bold;\n"
"font-family: Comic Neue;\n"
"\n"
"}")
        self.labelDica.setAlignment(QtCore.Qt.AlignCenter)
        self.labelDica.setObjectName("labelDica")
        self.verticalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(580, 210, 181, 281))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.anoLabel = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.anoLabel.setStyleSheet("QLabel{\n"
"font-size: 14px;\n"
"font: bold;\n"
"font-family: Comic Neue;\n"
"\n"
"}")
        self.anoLabel.setObjectName("anoLabel")
        self.verticalLayout.addWidget(self.anoLabel)
        self.motorLabel = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.motorLabel.setStyleSheet("QLabel{\n"
"font-size: 14px;\n"
"font: bold;\n"
"font-family: Comic Neue;\n"
"\n"
"}")
        self.motorLabel.setObjectName("motorLabel")
        self.verticalLayout.addWidget(self.motorLabel)
        self.potenciaLabel = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.potenciaLabel.setStyleSheet("QLabel{\n"
"font-size: 14px;\n"
"font: bold;\n"
"font-family: Comic Neue;\n"
"\n"
"}")
        self.potenciaLabel.setObjectName("potenciaLabel")
        self.verticalLayout.addWidget(self.potenciaLabel)
        self.tracaoLabel = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.tracaoLabel.setStyleSheet("QLabel{\n"
"font-size: 14px;\n"
"font: bold;\n"
"font-family: Comic Neue;\n"
"\n"
"}")
        self.tracaoLabel.setObjectName("tracaoLabel")
        self.verticalLayout.addWidget(self.tracaoLabel)
        self.pushDica = QtWidgets.QPushButton(self.centralwidget)
        self.pushDica.setGeometry(QtCore.QRect(750, 130, 31, 31))
        self.pushDica.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushDica.setStyleSheet("QPushButton{\n"
"border: none;\n"
"color: none;\n"
"\n"
"}")
        self.pushDica.setText("")
        self.pushDica.setObjectName("pushDica")
        self.labelAcabouDicas = QtWidgets.QLabel(self.centralwidget)
        self.labelAcabouDicas.setGeometry(QtCore.QRect(580, 500, 201, 41))
        self.labelAcabouDicas.setStyleSheet("QLabel{\n"
"font-size: 14px;\n"
"\n"
"\n"
"}")
        self.labelAcabouDicas.setText("")
        self.labelAcabouDicas.setAlignment(QtCore.Qt.AlignCenter)
        self.labelAcabouDicas.setObjectName("labelAcabouDicas")
        self.acertouErrou = QtWidgets.QLabel(self.centralwidget)
        self.acertouErrou.setGeometry(QtCore.QRect(30, 500, 121, 61))
        self.acertouErrou.setStyleSheet("QLabel{\n"
"font-size: 16px;\n"
"font: bold;\n"
"font-family: Comic Neue;\n"
"\n"
"}")
        self.acertouErrou.setText("")
        self.acertouErrou.setAlignment(QtCore.Qt.AlignCenter)
        self.acertouErrou.setObjectName("acertouErrou")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.Titulo.setText(_translate("MainWindow", "Adivinhe o Carro"))
        self.tentativas.setText(_translate("MainWindow", "Tentativas: 0"))
        self.inputCarro.setPlaceholderText(_translate("MainWindow", "Escreva aqui "))
        self.desistir.setText(_translate("MainWindow", "Desistir"))
        self.confirmar.setText(_translate("MainWindow", "Confirmar"))
        self.labelDica.setText(_translate("MainWindow", "Dicas"))
        self.anoLabel.setText(_translate("MainWindow", "Ano: "))
        self.motorLabel.setText(_translate("MainWindow", "Motor: "))
        self.potenciaLabel.setText(_translate("MainWindow", "Potência: "))
        self.tracaoLabel.setText(_translate("MainWindow", "Tração: "))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
